/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.idcardsystem;

import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.awt.Color;
import java.awt.Insets;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author arunt
 */
public class register extends javax.swing.JFrame {

    /**
     * Creates new form register
     */
    public register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1_ID = new javax.swing.JTextField();
        jTextField2_name = new javax.swing.JTextField();
        jTextField3_username = new javax.swing.JTextField();
        jLabel3_id = new javax.swing.JLabel();
        jLabel4_name = new javax.swing.JLabel();
        jLabel5_username = new javax.swing.JLabel();
        jLabel6_pass = new javax.swing.JLabel();
        jRadioButton2_student = new javax.swing.JRadioButton();
        jRadioButton1_admin = new javax.swing.JRadioButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1_REGISTER = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(226, 55, 98));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Register");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\arunt\\OneDrive\\Pictures\\Screenshot 2023-06-15 090212.png")); // NOI18N

        jTextField1_ID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField1_ID.setForeground(new java.awt.Color(204, 204, 204));
        jTextField1_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_IDActionPerformed(evt);
            }
        });

        jTextField2_name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField2_name.setForeground(new java.awt.Color(204, 204, 204));
        jTextField2_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2_nameActionPerformed(evt);
            }
        });

        jTextField3_username.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField3_username.setForeground(new java.awt.Color(204, 204, 204));
        jTextField3_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3_usernameActionPerformed(evt);
            }
        });

        jLabel3_id.setFont(new java.awt.Font("OCR A Extended", 0, 20)); // NOI18N
        jLabel3_id.setText("ID Number");

        jLabel4_name.setFont(new java.awt.Font("OCR A Extended", 0, 20)); // NOI18N
        jLabel4_name.setText("Fullname");

        jLabel5_username.setFont(new java.awt.Font("OCR A Extended", 0, 20)); // NOI18N
        jLabel5_username.setText("Username");

        jLabel6_pass.setFont(new java.awt.Font("OCR A Extended", 0, 20)); // NOI18N
        jLabel6_pass.setText("Set Password");

        buttonGroup1.add(jRadioButton2_student);
        jRadioButton2_student.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        jRadioButton2_student.setText("Student");

        buttonGroup1.add(jRadioButton1_admin);
        jRadioButton1_admin.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        jRadioButton1_admin.setText("Admin");

        jButton1_REGISTER.setBackground(new java.awt.Color(226, 55, 98));
        jButton1_REGISTER.setFont(new java.awt.Font("OCR A Extended", 0, 21)); // NOI18N
        jButton1_REGISTER.setText("Register");
        jButton1_REGISTER.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1_REGISTERMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1_REGISTERMouseExited(evt);
            }
        });
        jButton1_REGISTER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_REGISTERActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(51, 118, 143));
        jButton1.setFont(new java.awt.Font("OCR A Extended", 0, 21)); // NOI18N
        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3_id)
                    .addComponent(jLabel4_name)
                    .addComponent(jLabel5_username)
                    .addComponent(jLabel6_pass))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1_ID, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2_name, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3_username, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(81, 81, 81))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton1_admin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton2_student))
                            .addComponent(jButton1_REGISTER, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE))
                        .addGap(0, 91, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3_id))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2_name, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4_name))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3_username, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5_username))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6_pass))))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton2_student)
                    .addComponent(jRadioButton1_admin))
                .addGap(40, 40, 40)
                .addComponent(jButton1_REGISTER, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2_nameActionPerformed

    private void jTextField1_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_IDActionPerformed

    private void jTextField3_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3_usernameActionPerformed

    private void jButton1_REGISTERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_REGISTERActionPerformed

        boolean err=false;
        String adminkey="NOT_ADMIN";
        String Id= jTextField1_ID.getText();
        String Name= jTextField2_name.getText();
        String Username =jTextField3_username.getText();
        String Password =jPasswordField1.getText();

        if(Username.isEmpty()||Password.isEmpty()||Id.isEmpty()||Name.isEmpty()){
            JOptionPane.showMessageDialog(this, "All fields are compulsory \ncan't be empty ", "ERROR",JOptionPane.ERROR_MESSAGE);
            err=true;
        }
        else if(!jRadioButton1_admin.isSelected()&&!jRadioButton2_student.isSelected()){
            JOptionPane.showMessageDialog(this, "Choose Access level (Admin/Student)", "ERROR",JOptionPane.ERROR_MESSAGE);
            err=true;
        }
        if(jRadioButton1_admin.isSelected()&&!err){
            adminkey =JOptionPane.showInputDialog(this, "Enter ADMIN KEY", "Authentication", HEIGHT);
        }
        if(!err){
            boolean success=Authentication.register(Id,Name,Username,Password,adminkey);
            System.out.println(success+"HSDI");
            if(success){
                JOptionPane.showMessageDialog(this, "User successfully registered !!!", "ERROR",JOptionPane.OK_OPTION);
                dispose();
            }
        }
    }//GEN-LAST:event_jButton1_REGISTERActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1_REGISTERMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1_REGISTERMouseEntered
        // TODO add your handling code here:
        jButton1_REGISTER.setBackground(new java.awt.Color(126, 40, 62));
    }//GEN-LAST:event_jButton1_REGISTERMouseEntered

    private void jButton1_REGISTERMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1_REGISTERMouseExited
        // TODO add your handling code here:
         jButton1_REGISTER.setBackground(new java.awt.Color(226, 55, 98));
    }//GEN-LAST:event_jButton1_REGISTERMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new FlatMacLightLaf());

            UIManager.put("ScrollBar.trackArc", 999);
            UIManager.put("ScrollBar.thumbArc", 999);
            UIManager.put("ScrollBar.trackInsets", new Insets(2, 4, 2, 4));
            UIManager.put("ScrollBar.thumbInsets", new Insets(2, 2, 2, 2));
            UIManager.put("ScrollBar.track", new Color(0xe0e0e0));
            UIManager.put("Button.arc", 999);
            UIManager.put("Component.arc", 999);
            UIManager.put("ProgressBar.arc", 999);
            UIManager.put("TextComponent.arc", 999);

        } catch (Exception e) {
            e.printStackTrace();
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton1_REGISTER;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3_id;
    private javax.swing.JLabel jLabel4_name;
    private javax.swing.JLabel jLabel5_username;
    private javax.swing.JLabel jLabel6_pass;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JRadioButton jRadioButton1_admin;
    private javax.swing.JRadioButton jRadioButton2_student;
    private javax.swing.JTextField jTextField1_ID;
    private javax.swing.JTextField jTextField2_name;
    private javax.swing.JTextField jTextField3_username;
    // End of variables declaration//GEN-END:variables
}
